[api_settings]
rpc_urls = [
    { name = "Singapore", url = "https://rpc.monad-testnet-5.fastlane.xyz/FFHEYATiGl2Q83xOnf71ltrqZ57q9U1W" },
    { name = "London", url = "https://rpc.monad-testnet-2.fastlane.xyz/b3qFoDfY9sR44yRyOeHAfyj9dpEXVoOC" },
    { name = "Bogota", url = "https://rpc.monad-testnet-3.fastlane.xyz/j6EsEZHfw9Iqrp7DUX5e1aLUk85d1Yzw" }
]

[game_settings]
frontrunner_contract_address = '0xBce2C725304e09CEf4cD7639760B67f8A0Af5bc4'
abi_string = '[{"type":"function","name":"frontrun","inputs":[],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"getScore","inputs":[{"name":"participant","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"tuple","internalType":"struct Score","components":[{"name":"wins","type":"uint128","internalType":"uint128"},{"name":"losses","type":"uint128","internalType":"uint128"}]}],"stateMutability":"view"},{"type":"function","name":"getScores","inputs":[],"outputs":[{"name":"","type":"tuple[]","internalType":"struct Frontrunner.ParticipantData[]","components":[{"name":"Address","type":"address","internalType":"address"},{"name":"Wins","type":"uint256","internalType":"uint256"},{"name":"Losses","type":"uint256","internalType":"uint256"}]}],"stateMutability":"view"}]'

[eoa]
private_key = 'ffd8039163cc9334a8b1f455517effa8f9e1e8ed4caf7634823694674390703b'